version: '3.3'

networks:
  internal_network:

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: '${APP_NAME}-server'
    ports:
      - '${APP_PORT}:80'
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
